M48
; DRILL file {KiCad 7.0.8} date Fri Nov 10 09:55:42 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-11-10T09:55:42+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X115.18Y-82.105
X115.18Y-87.885
T2
X119.895Y-129.63
X175.51Y-129.63
T0
M30
